# mapping_script.sh
# Author: Gloor-lab Western University
# Modified by: Jia Rong Wu
# jwu424 (at) gmail.com
# 
# Description: Script to utilize the SAMfiles generated by mapping.sh in order to create a set of counts with HTSeq.scripts.count

SAMLOCATION="../simulated_reads/samfiles/*"
MAPLOCATION="../simulated_reads/mapped/"
MAPFIXLOCATION="../simulated_reads/mapped_fixed/"
HTSLOCATION="../simulated_reads/htsequencecounts/"
GFFLOCATION="../source_files_barton_yeast/yeast.gff"
CNTSTXT="_counts.txt"
for file in $SAMLOCATION
do
	if [ ${file: -4} == ".sam" ]; then # check that it does indeed end in the .sam file extension
		filename=$(basename $file) # omit the directory leading up the file name
		filenamenoext="${filename%.*}" # Get the filename without an extension
		# create a new file with the same name but in directory mapped_fixed/
		# directory was already created through "mkdir mapped_fixed"
	
		echo "Working on" $filename"..." 
		awk 'BEGIN {OFS="\t"}; {gsub("^.*NC_", "|NC_", $3); gsub("\\|", "", $3); print}' $SAMLOCATION$filename > $MAPFIXLOCATION$filename
		# It isn't as good as I wanted... It would have been nice to not include "|NC_" as part of the subtitution
		# Instead of replace with itself. Would have been better to be able to select everything before that.
		# But testing this on ERR459206.sam appeared to do the job...

		# Now the counts. Do htseq-count on the mapped_fixed
		python -m HTSeq.scripts.count -f sam -t gene -i locus_tag -a 0 $MAPFIXLOCATION$filename $GFFLOCATION > $HTSLOCATION$filenamenoext$CNTSTXT

		# Cleanup. Delete the mapped_fixed sam file
		rm $MAPFIXLOCATION$filename

		echo "Done" $filename"."
	fi
done

# Cleanup. Delete the now-empty mapped_fixed directory
rmdir mapped_fixed
